# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Cloud Screener

on:
  issues:
      types:
        - opened
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run-screener:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the version of Python you need

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

          - name: Create service_account.json
          run: |
            echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" | jq '.' > ./screener/service_account.json

        # Step 4: Check out the environment file (e.g., .env file)
      - name: Set environment variables
        run: |
          echo "FMP_KEY=${{ secrets.FMP_KEY }}" >> $GITHUB_ENV

      # Step 5: Run the cloud screener script
      - name: Run Cloud Screener
        run: |
          python cloud_screener.py