# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Cloud Screener

on:
  issues:
      types:
        - opened
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run-screener:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create directory for service account
        run: mkdir -p ./screener  
      
      - name: Create service_account.json
        run: |
          echo '${{ toJson(fromJson(secrets.SERVICE_ACCOUNT_JSON)) }}' > ./screener/service_account.json

      - name: Set environment variables
        run: |
          echo "FMP_KEY=${{ secrets.FMP_KEY }}" >> $GITHUB_ENV

      - name: Run Cloud Screener
        run: |
          python cloud_screener.py